### PR TITLE
feat(dashboard): post layout and infinite scroll

### LINKED ISSUE #1: feat(dashboard): post layout and infinite scroll
Dashboard post

### PR DESCRIPTION
**Pull request by Marob-nod**
Closes #1

### CODE REVIEW

**Comment by Marob-nod** [comment]
Thanks for your comments. I am reviewing my code right now. I can't auto indent my code while saving even if my mode is On in my settings. Do you know how i can add that to VS code ?

**Comment by nicobao** [comment]
> Thanks for your comments. I am reviewing my code right now. I can't auto indent my code while saving even if my mode is On in my settings. Do you know how i can add that to VS code ?

Have you downloaded vscode-eslint extension?
https://github.com/microsoft/vscode-eslint
The front currently does not have prettier, just eslint.
It uses `.eslint.cjs`. In case it still does not work, try: https://github.com/microsoft/vscode-eslint/issues/1456

**Comment by Marob-nod** [comment]
> > Thanks for your comments. I am reviewing my code right now. I can't auto indent my code while saving even if my mode is On in my settings. Do you know how i can add that to VS code ?
> 
> Have you downloaded vscode-eslint extension? https://github.com/microsoft/vscode-eslint The front currently does not have prettier, just eslint. It uses `.eslint.cjs`. In case it still does not work, try looking at: [microsoft/vscode-eslint#1456](https://github.com/microsoft/vscode-eslint/issues/1456)

Es-lint shows the erros of my code but to indent it correctly

**Comment by nicobao** [comment]
I think you closed the PR by accident!

**Comment by Marob-nod** [comment]
Oh yeah my bad, i juste reopened it !

**Comment by nicobao** [comment]
> > > Thanks for your comments. I am reviewing my code right now. I can't auto indent my code while saving even if my mode is On in my settings. Do you know how i can add that to VS code ?
> > 
> > 
> > Have you downloaded vscode-eslint extension? https://github.com/microsoft/vscode-eslint The front currently does not have prettier, just eslint. It uses `.eslint.cjs`. In case it still does not work, try looking at: [microsoft/vscode-eslint#1456](https://github.com/microsoft/vscode-eslint/issues/1456)
> 
> Es-lint shows the erros of my code but to indent it correctly

Just added prettier it should work now.

**Comment by nicobao** [comment]
For info, I also harmonized the eslint config across the services

**Pull request closed without merging**
